# /etc/prometheus/file_sd/node_targets.yml
- targets:
    - "10.0.0.51:9100"   # Node Exporter
    - "10.0.0.41:9100"
    - "10.0.0.31:9100"
  labels:
    group: "rocky9_nodes"
    env: "lan"

# 如果还有其他 exporter，可以再写一个文件
# /etc/prometheus/file_sd/other_exporters.yml
- targets:
    - "10.0.0.51:9104"   # 举例 MySQL Exporter
  labels:
    job: "mysql"
