# kubeadm-config.yaml 例子
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
certificatesDir: /etc/kubernetes/pki
apiServer:
  certSANs:
    - 10.0.0.168   # VIP
    - 10.0.0.61    # 本机 IP
    - 127.0.0.1
    - kubernetes
    - kubernetes.default

