apiVersion: v1
kind: Secret
metadata:
  name: traefik-dashboard-auth-secret
  namespace: traefik
type: Opaque   # 或 kubernetes.io/basic-auth 也可以，但 Opaque 最通用
data:
  users: |    # 注意这里用 | ，但内容必须是单行（无尾换行）
    YWRtaW46JGFwcjEkQXNQcXc4VEIkREt6WlhPSC5QaHkxTmhBMEk4dVZ3Lg==
